### ISSUE TITLE
使用 uwgsi 时，close websocket 时报错:uwsgi_response_write_headers_do(): Bad file descriptor [core/writer.c line 238] during GET /echo (127.0.0.1) IOError: write error

### ISSUE THREAD

**Issue by raugher** [duanhongyi/dwebsocket#14]
您好， 
1、使用 uwgsi 时，close websocket 时报错
`uwsgi_response_write_headers_do(): Bad file descriptor [core/writer.c line 238] during GET /echo (127.0.0.1) IOError: write error 。`
2、如果运行 run_eventlet.py，close websocket  时，能正常关闭。
3、运行 python manage.py runserver , close websocket 时，报错
`
[14/May/2016 07:45:55] "GET / HTTP/1.1" 200 1466
[14/May/2016 07:46:03] "GET /echo HTTP/1.1" 200 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
## [14/May/2016 07:46:03] "GET /echo HTTP/1.1" 500 59

Exception happened during processing of request from ('127.0.0.1', 33492)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 99, in **init**
    super(WSGIRequestHandler, self).**init**(_args, *_kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in **init**
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
----------------------------------------`

其中 所有浏览器  1 和 3都报错。

uwgsi install后的输出：
`################# uWSGI configuration #################

```
pcre = True
kernel = Linux
malloc = libc
execinfo = False
ifaddrs = True
ssl = True
zlib = True
locking = pthread_mutex
plugin_dir = .
timer = timerfd
yaml = embedded
json = False
filemonitor = inotify
routing = True
debug = False
ucontext = True
capabilities = False
xml = expat
event = epoll

############## end of uWSGI configuration #############
total build time: 20 seconds
*** uWSGI is ready, launch it with /usr/local/bin/uwsgi ***`
```

版本：python2.7 + django1.9.5 +uwgsi2.0.13.1
我安装低版本的uwgsi，结果是一样的。

**Comment by duanhongyi** [comment]
@raugher  目前dwebsocket仅在gevent/eventlet + nginx上测试比较充分，其他环境目前正在调试。
