### ISSUE TITLE
前端刷新重连，dwebsocket抛异常

### ISSUE THREAD

**Issue by yyjinlong** [duanhongyi/dwebsocket#15]
我的情况是，前端首先发出一个ajax请求去异步响应一个事件。在ajax调用后，会发出web socket消息给后端，当界面刷新时，抛出如下异常，同时ajax响应也会因为这个得不到结果。

Traceback (most recent call last):
  File "/home/q/python/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/home/q/python/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/home/q/python/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/home/q/python/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/home/q/python/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/home/q/python/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/home/q/python/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/home/q/python/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor

**Comment by duanhongyi** [comment]
嗯，开发环境会有这个问题，部署时请使用eventlet或gevent。参见examples目录的run_eventlet.py

**Comment by yyjinlong** [comment]
嗯 好的 感谢。我是用gunicorn+gevent来启动的，我再观察一下运行情况。

**Comment by nbwhg** [comment]
请问这个问题修复了吗？我是开发环境，一切正常 ， 当前端 close() 得时候  后端就会报这个错误

**Comment by su6838354** [comment]
@duanhongyi example里面的有同样问题吧？只不过他try 掉了
