### ISSUE TITLE
websocket前端链接抛异常

### ISSUE THREAD

**Issue by Cainrin** [duanhongyi/dwebsocket#16]
dwebsocket前端起链接时直接抛异常
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/SocketServer.py", line 595, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/python27/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/python27/lib/python2.7/site-packages/Django-1.8.12-py2.7.egg/django/core/servers/basehttp.py", line 102, in **init**
    super(WSGIRequestHandler, self).**init**(_args, *_kwargs)
  File "/usr/local/python27/lib/python2.7/SocketServer.py", line 653, in **init**
    self.finish()
  File "/usr/local/python27/lib/python2.7/SocketServer.py", line 712, in finish
    self.wfile.close()
  File "/usr/local/python27/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/local/python27/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor

**Comment by zhaozhong** [comment]
我也遇到同样的问题，同问

**Comment by hanboyuan** [comment]
调用request.websocket.close()方法的时候报错,同问

**Comment by jabbawockeez** [comment]
同问+1

**Comment by lemon65535** [comment]
同问，找不到原因
