### ISSUE TITLE
64位win7，py3.5，django1.10.4报错！

### ISSUE THREAD

**Issue by toop** [duanhongyi/dwebsocket#21]
64位win7，py3.5，django1.10.4报错！

Traceback (most recent call last):
  File "D:\xxx\lib\site-packages\django\core\handlers\exception.py", line
 39, in inner
    response = get_response(request)
  File "D:\xxx\lib\site-packages\django\core\handlers\base.py", line 187,
 in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\xxx\lib\site-packages\django\core\handlers\base.py", line 185,
 in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\xxx\lib\site-packages\django\utils\decorators.py", line 149, i
n _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\xxx\lib\site-packages\dwebsocket\decorators.py", line 16, in n
ew_func
    response = func(request, *args, **kwargs)
  File "D:\xxx\ems\eim\views.py", line 1157, in realtimesalesdata
    request.websocket.send(json.dumps(message)) #.encode().decode('unicode-escap
e')) #,ensure_ascii=False))
  File "D:\xxx\lib\site-packages\dwebsocket\backends\default\websocket.py
", line 41, in send
    self.protocol.write(message)
  File "D:\xxx\lib\site-packages\dwebsocket\backends\default\protocols.py
", line 236, in write
    self._write_frame(True, opcode, message)
  File "D:\xxx\lib\site-packages\dwebsocket\backends\default\protocols.py
", line 224, in _write_frame
    frame += data
TypeError: can't concat bytes to str

Traceback (most recent call last):
  File "d:\python35\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "D:\ems-d110p3\lib\site-packages\django\core\servers\basehttp.py", line 9
5, in handle_error
    super(ServerHandler, self).handle_error()
  File "d:\python35\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "d:\python35\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "d:\python35\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "d:\python35\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "d:\python35\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python35\Lib\socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "d:\python35\Lib\socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "d:\python35\Lib\socketserver.py", line 681, in __init__
    self.handle()
  File "D:\ems-d110p3\lib\site-packages\django\core\servers\basehttp.py", line 1
74, in handle
    handler.run(self.server.get_app())
  File "d:\python35\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "d:\python35\Lib\wsgiref\simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
failed: Error during WebSocket handshake: Unexpected response code: 400
求助解决办法，谢谢！

**Comment by caomingjiang** [comment]
我也遇到同样的问题，关掉客户端的连接，就会报这样的错，怎么解决的呢？
