### ISSUE TITLE
当 socket 被关闭时，会报错 "error: [Errno 9] Bad file descriptor"

### ISSUE THREAD

**Issue by pang-w** [duanhongyi/dwebsocket#3]
django 1.7.8
python manage.py runserver 0.0.0.0:8080

前端浏览器：

```
var ws = WebSocket('http://192.168.33.1/ws');
ws.send('test');
ws.close(); // 执行这里会报错
```

后端django：

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 210, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 268, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 189, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 389, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
----------------------------------------
Exception happened during processing of request from ('192.168.33.1', 62509)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 582, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 129, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 640, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 693, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
----------------------------------------
```

**Comment by duanhongyi** [comment]
@pang-w

浏览器版本是什么？

**Comment by pang-w** [comment]
@duanhongyi chrome 43.0.2357.130 在其他浏览器中也是这样：）

**Comment by duanhongyi** [comment]
@pang-w

使用gevent或者eventlet有这个问题吗？

**Comment by pang-w** [comment]
@duanhongyi 都尝试了，另外 使用uwsgi + nginx 会 bad request 400错误。

**Comment by duanhongyi** [comment]
@pang-w

好我看看

**Comment by pang-w** [comment]
@duanhongyi 谢谢，比较主要的就是 uwsgi + nginx 会 bad request 400

**Comment by duanhongyi** [comment]
@pang-w
1、克隆最新的代码安装，git clone https://github.com/duanhongyi/dwebsocket

2、在settings中配置
WEBSOCKET_FACTORY_CLASS = 'dwebsocket.backends.uwsgi.factory.uWsgiWebSocketFactory'

3、uwsgi编译时增加libssl-dev支持

4、启动uwsgi时使用--http-websockets参数
uwsgi --http :8080 --http-websockets --processes 1 --wsgi-file examples/wsgi.py  --async 30 --ugreen

目前在实验阶段，不太稳定。

**Comment by pang-w** [comment]
棒棒的，我尝试一下，然后如果可以了，我反馈给你：）

**Comment by shenqihui** [comment]
:+1:  
调试了很久，发现少了个东西 ， eventlet ，不然再 uwsgi 上面总会出现 400 或者 500 的状态码。

**Comment by pang-w** [comment]
已搞定！

**Comment by icyfanfan** [comment]
请问楼上两位怎么搞定的，我也是一直出现400状态码，已经安装eventlet
@shenqihui  @pang-w

**Comment by shenqihui** [comment]
@icyfanfan  
uwsgi 方式可用了。。。runserver 方式不 ok 。。。。。

@duanhongyi     uwsgi  方式弄好了， runserver 或者 run_eventlet.py 启动方式就直接 400 。求解决方法。

**Comment by duanhongyi** [comment]
@icyfanfan 
@shenqihui 

如果是普通的方式需要将settings中的WEBSOCKET_FACTORY_CLASS删除掉，即使用默认的实现。
WEBSOCKET_FACTORY_CLASS = 'dwebsocket.backends.uwsgi.factory.uWsgiWebSocketFactory'

**Comment by SparksFyz** [comment]
@pang-w  @duanhongyi        how to fix  `Bad file descriptor`....   (I use django server)

**Comment by duanhongyi** [comment]
@SparksFyz 

git clone https://github.com/duanhongyi/dwebsocket
cd dwebsocket/examples
vagrant up
vagrant ssh
cd /vagrant_data/examples
./init.sh
python manage.py runserver 0.0.0.0:8000
