### ISSUE TITLE
本机开发环境，websocket能正常连接，部署到服务器上，uwsgi+websocket 连接成功后立马断开

### ISSUE THREAD

**Issue by beyondh** [duanhongyi/dwebsocket#41]
本机开发环境，websocket能正常连接，部署到服务器上，Nginx+uwsgi+websocket 连接成功后立马断开，Nginx上已经开始支持websocket，不知道是什么问题？

**Comment by duanhongyi** [comment]
更改WEBSOCKET_FACTORY_CLASS  了？

**Comment by duanhongyi** [comment]
@beyondh

**Comment by chenzetao** [comment]
同样问题，wsgi.ini和settings都加了factory，好像是view.py里accept_websocket下面部分不能保持长连，执行完立刻断开

**Comment by chenzetao** [comment]
贴一下报错：
麻烦作者大大@duanhongyi 有时间的时候看下

`Internal Server Error: /echo
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./pb_monitor/views.py", line 33, in echo
    lock.release()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dwebsocket/backends/default/websocket.py", line 41, in send
    self.protocol.write(message)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dwebsocket/backends/default/protocols.py", line 236, in write
    self._write_frame(True, opcode, message)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dwebsocket/backends/default/protocols.py", line 224, in _write_frame
    frame += data
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 0: ordinal not in range(128)`

**Comment by chenzetao** [comment]
我找到我的问题了，ugreen是以插件形式提供的，默认的uwsgi内核是不包括ugreen的，所以async模式启动会导致异步切换的时候出错
解决的方法是，下载uwsgi的安装包（ https://projects.unbit.it/downloads/uwsgi-latest.tar.gz ），解压后在plugin目录下能看到ugreen插件的源文件，用uwsgidecorators.py命令将ugreen编译成ugreen_plugin.so文件，然后放到uwsgi的二进制文件同目录下
在uwsgi.ini配置文件中，加入plugin=ugreen参数，原有的async=30和ugreen=true保留
然后重启一下uwsgi就正常了
如果还遇到断开的问题，就检查一下uwsgi和nginx的各种超时时间，包括uwsgi里的harakiri=300，http-timeout = 300，和nginx里的uwsgi_read_timeout 300; uwsgi_ignore_client_abort on; proxy_connect_timeout 300;
长期优化的话，增加客户端加上心跳机制

**Comment by duanhongyi** [comment]
OK
