### ISSUE TITLE
使用uwsgi+django+gevent时报错：读取客户端数据时报错IOError: unable to fd 14 to the event queue

### ISSUE THREAD

**Issue by SweetBullet** [duanhongyi/dwebsocket#42]
一旦调用wait()或者iter迭代器，就会出现以下报错：
请问以下是什么原因呢？
-------------------------------------------------------分割线----------------------------------
Tue Sep 18 16:31:05 2018 - ASYNC call without async mode !!!
Internal Server Error: /ws_connect
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./OuterServer/Chat/service.py", line 199, in ws_connect
    for message in request.websocket:
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/websocket.py", line 55, in __iter__
    message = self.wait()
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/backends/default/websocket.py", line 87, in wait
    new_data = self.protocol.read()
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/backends/default/protocols.py", line 52, in read
    _, data = self.read_data()
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/backends/default/protocols.py", line 98, in read_data
    fin, opcode, data = self.read_frame()
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/backends/default/protocols.py", line 123, in read_frame
    header_bytes = self._read_strict(2)
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/backends/default/protocols.py", line 150, in _read_strict
    _buffer = self.sock.recv(bufsize)
  File "/usr/local/lib/python2.7/dist-packages/dwebsocket/backends/uwsgi/factory.py", line 18, in recv
    uwsgi.wait_fd_read(self.fileno(), -1)
IOError: unable to fd 14 to the event queue

**Comment by SweetBullet** [comment]
有人有同样的错误吗，在线等

**Comment by duanhongyi** [comment]
> 有人有同样的错误吗，在线等

只用一个吧，django+gevent

**Comment by wenbc** [comment]
这个怎么搞定的？
