### ISSUE TITLE
python 3.6,+Django 2.1.2+dwebsocket 0.5.4 前端只要一连接时就提示：ValueError: timeout must be non-negative

### ISSUE THREAD

**Issue by kevinloveross** [duanhongyi/dwebsocket#43]
前端js代码如下：
```
$(function () {
        $('#connect_websocket').click(function () {
            if (window.s) {
                window.s.close()
            }
            /*创建socket连接*/
            var socket = new WebSocket("ws://" + window.location.host + "/echo");
            socket.onopen = function () {
                console.log('WebSocket open');//成功连接上Websocket
            };
            socket.onmessage = function (e) {
                console.log('message: ' + e.data);//打印出服务端返回过来的数据
                $('#messagecontainer').prepend('<p>' + e.data + '</p>');
            };
            // Call onopen directly if socket is already open
            if (socket.readyState === WebSocket.OPEN) socket.onopen();
            window.s = socket;
        });
        $('#send_message').click(function () {
            //如果未连接到websocket
            if (!window.s) {
                alert("websocket未连接.");
            } else {
                window.s.send($('#message').val());//通过websocket发送数据
            }
        });
        $('#close_websocket').click(function () {
            if (window.s) {
                window.s.close();//关闭websocket
                console.log('websocket已关闭');
            }
        });

    });

```
后端代码：
```
@accept_websocket
def echo(request):
    print(request.is_websocket())
    if not request.is_websocket():
        try:
            message = request.GET['message']
            return HttpResponse(message)
        except:
            return render(request, 'index.html')
    else:
        
        for message in request.websocket:
            print('llll',message)
            request.websocket.send(message)
```

错误信息：
Internal Server Error: /echo
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "/Users/xxxxx/PycharmProjects/xxxxx/xxxxx/views.py", line 29, in echo
    for message in request.websocket:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dwebsocket/websocket.py", line 55, in __iter__
    message = self.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dwebsocket/backends/default/websocket.py", line 89, in wait
    if self.protocol.can_read(timeout=timeout):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dwebsocket/backends/default/protocols.py", line 197, in can_read
    r, w, e = select.select(r, w, e, timeout)
ValueError: timeout must be non-negative
[15/Oct/2018 17:23:07] "GET /echo HTTP/1.1" 500 86248

如果我在把wait()的默认值必为整数就不出现问题，但是一但timeout一样也会出现这个问题
    def __iter__(self):
   ```
     '''
        Use ``WebSocket`` as iterator. Iteration only stops when the websocket
        gets closed by the client.
        '''
        while True:
            message = self.wait()
            yield message
            if message is None:
                break
```

请大神帮助解决一下！

**Comment by kevinloveross** [comment]
我退回到0.4.2就没有这个问题了

**Comment by duanhongyi** [comment]
I fixed this problem. 
`pip install dwebsocket --upgrade`

**Comment by duanhongyi** [comment]
@kevinloveross

**Comment by kevinloveross** [comment]
thanks @duanhongyi , I have upgrade and the issue already fixed in new version.
