### ISSUE TITLE
传输数据量过大，会造成 ws 关闭的问题。

### ISSUE THREAD

**Issue by shenqihui** [duanhongyi/dwebsocket#6]
环境：py2.7, dwebsocket v0.4.2(pypi版本), ubuntu 14.04（vagrant 虚拟机) ，分配 1G RAM）
启动方式： python manage.py runserver 0.0.0.0:8880

目前测试了下，超过特定长度的字符串发送，就会造成 websocket 的 onclose 。目前尝试过，发送 15w 长度的字符串，就会造成错误。

但是，存在一个奇特的现象。第一次发送例子里面的 hello world 字符串，再次发送 15w 长度的字符串，就没发生 onclose 错误了。

为避免错误，目前我的做法是，大于 5w 长度的字符串，就使用 post 进行发送。

希望能解决。

index.html 改造如下：

``` javascript
$(function () {
        var s = new WebSocket("ws://" + window.location.host + "/echo");
        s.onopen = function () {
            console.log('WebSocket open');
        };
        s.onmessage = function (e) {
            // console.log('message: ' + e.data);
            $('#messagecontainer').append('<p>' + e.data + '</p>');
        };
        s.onclose = function (e) {
            console.log('WebSocket close');
        }
        window.s = s;
        $('#send_message').click(function () {
            var send = $('#message').val();
            if(!window.s){
                alert("Please connect server.");
            }else{
                console.log(send.length);
                s.send(send);
            }
        });
    });
```

``` html
<textarea name="message" id="message" cols="30" rows="10">Hello, World!</textarea>
```

服务器端错误信息 

```
[10/Sep/2015 21:43:32] "GET /echo HTTP/1.1" 500 466607
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 191, in send_preamble
    self._write('HTTP/%s %s\r\n' % (self.http_version,self.status))
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 391, in _write
    self.stdout.write(data)
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
[10/Sep/2015 21:43:32] "GET /echo HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('192.168.102.1', 49920)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 129, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor
----------------------------------------
```

**Comment by duanhongyi** [comment]
@shenqihui

是否尝试eventlet/gevent。

**Comment by shenqihui** [comment]
@duanhongyi  
不好意思，没看到提醒，回复晚了。

当时用的是例子里面的启动方法。

```
uwsgi --http :8080 --http-websockets --processes 1 \
--wsgi-file wsgi.py--async 30 --ugreen --http-timeout 300
```

**Comment by duanhongyi** [comment]
@shenqihui 

uwsgi没有在生产环境下测试过，但是使用gevent或者eventlet无此问题；但是我发现在某些浏览器(chrome)下超过一定数量就会发生异常，而在firefox以及使用websocket-client(python)无此问题。

**Comment by shenqihui** [comment]
@duanhongyi  明白。
